### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by ErrorRExorY** [algolia/sup3rS3cretMes5age#100]
Hey, I will just add this here if anyone else has this problem, since I have docker-compose and docker compose, it was confusing, but I had to specify the Vault version in the docker compose file

```
version: '3.2'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: supersecret
    cap_add:
      - IPC_LOCK
    expose:
      - 8200

  supersecret:
    build: ./
    image: algolia/supersecretmessage:latest
    container_name: supersecret
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: supersecret
      SUPERSECRETMESSAGE_HTTP_BINDING_ADDRESS: ":8082"
    ports:
      - "8082:8082"
    depends_on:
      - vault

**Comment by logiczny** [comment]
I had exact problem like yours, adding version instead of a `latest` solved the problem.

**Comment by CaptainExorY** [comment]
> I had exact problem like yours, adding version instead of a `latest` solved the problem.

Exactly what I added above, but thanks for clarifying!

**Comment by AlienPie** [comment]
According to https://hub.docker.com/_/vault, 'vault' has been deprecated and should be replaced with hashicorp/vault. This worked for me.
