### ISSUE TITLE
https gives 500 error

### ISSUE THREAD

**Issue by bbcolo** [algolia/sup3rS3cretMes5age#16]
Hi, 

After `make run VIRTUAL_HOST=<MY_DOMAIN> `
I receive a 500 error when accessing my URL. 
It seems the letsencrypt is not properly doing his job. Although i dont see any errors when running:
`make logs `

One thing I notice is the following from nginx/conf.d/default.conf:

...      
server {
        server_name <MY_DOMAIN>;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        return 500; 
    ....

Can I conclude by the return 500 rule that SSL disabled intentionally?

Alternatively is it possible to use existing certificates?

**Comment by eranchetz** [comment]
@bbcolo can you please paste the exact run command and upload the logs?

**Comment by eranchetz** [comment]
@bbcolo sorry but after 14 days I am closing this :(
