### ISSUE TITLE
Button display issue

### ISSUE THREAD

**Issue by rayrutjes** [algolia/sup3rS3cretMes5age#19]
![image](https://user-images.githubusercontent.com/5570853/37864402-8a43fbe0-2f6e-11e8-9408-bf89963d5876.png)

**Comment by eranchetz** [comment]
@rayrutjes I am unable to reproduce this, what steps did you do get this?

**Comment by rayrutjes** [comment]
Not sure, I've been unable to re-produce locally.
Probably just affecting the version currently deployed in some weird scenario.
Closing it.
