### ISSUE TITLE
Not working with IE

### ISSUE THREAD

**Issue by yrmbrg** [algolia/sup3rS3cretMes5age#25]
Hi Team,

First, thanks for your work. I was search a very simple secret sharing tool that we con host ourself, I found yours and it is just what i needed.

However, your code isn't working on IE.

I made few ajustement to get it work with IE, that I'd like to share with you:

### In index.html, line 70:
```
success(data) {
...
```

triggers an error ("Expected ':'").

Could be replaced by:
```
success: function(data) {
...
```

### In index.html, line 94:
```
`${window.location.origin}/getmsg?token=${encodeURIComponent(token)}&filetoken=${encodeURIComponent(filetoken)}&filename=${encodeURIComponent(filename)}`
```

"`" character is not supported by IE.

Could be replaced by:
```
`window.location.origin+"/getmsg?token="+encodeURIComponent(token)+"&filetoken="+encodeURIComponent(filetoken)+"&filename="+encodeURIComponent(filename)
`
```

### In index.html, line 94:
```
`$("#url").text(`${window.location.origin}/getmsg?token=${encodeURIComponent(token)}`);`
```

Same error as above.

Could be replace by:
```
`$("#url").text( window.location.origin +"/getmsg?token="+encodeURIComponent(token) );`
```

### In getmsg.html.bak, line 76:
```
` let params = (new URL(window.location)).searchParams;`
```

URL function is not suported by IE.

This could be replaced by the following function:

```
function decodeUriComponentWithSpace (component) {
    return decodeURIComponent(component.replace(/\+/g, '%20'))
  }

  // type : 'hash', 'search' or 'both'
  function getLocationParameters (location, type) {
    if (type !== 'hash' && type !== 'search' && type !== 'both') {
      throw 'getLocationParameters expect argument 2 "type" to be "hash", "search" or "both"'
    }

    let searchString = typeof location.search === 'undefined' ? '' : location.search.substr(1)
    let hashString = typeof location.hash === 'undefined' ? '' : location.hash.substr(1)
    let queries = []
    if (type === 'search' || type === 'both') {
      queries = queries.concat(searchString.split('&'))
    }
    if (type === 'hash' || type === 'both') {
      queries = queries.concat(hashString.split('&'))
    }

    let params = {}
    let pair

    for (let i = 0; i < queries.length; i++) {
      if (queries[i] !== '') {
        pair = queries[i].split('=')
        params[this.decodeUriComponentWithSpace(pair[0])] = this.decodeUriComponentWithSpace(pair[1])
      }
    }
    return params
}
```

And so line 76 has to become:
```
`let params = getLocationParameters(window.location,"search");`
```

And all _params.get(fieldname)_, needs to be replaced by: _params.fieldname_ .

Line78:
`console.log(window.location.origin + "/secret?token=" + params.token + "&filetoken=" + params.filetoken + "&filename=" + params.filename );
`          

Line 81:
`url: window.location.origin + "/secret?token=" + params.token,`

Line 85:
`showMsg(data.msg, params.filetoken, params.filename)`

### In getmsg.html, line 97:

`$('#textarea1').text(msg)`

Doesn't trigger an error. but, by using this property, when the user that receive the message focuses on the field (for text selection), the filed is erased.

Could be replaced by:
`$('#textarea1').val(msg)`

I joined the two modified files.
[index_getmsg_modified.zip](https://github.com/algolia/sup3rS3cretMes5age/files/3309503/index_getmsg_modified.zip)

I did all these changes, and it seems to work as it should on IE 11.
Also tested on Chrome and seems to work.

Hope this could help users of this project.

By the way:
README.md could be a little bit more detailled.
Installation have been a bit tricky. I had to search a bit for errors solving when running make commands:
- GO installation by itself is not enough, you need also to download "dep" tool.
- Supersecret directory need to be placed in $GOPATH/src in order to work

I need to make a fresh installation and a how to in order to deploy this tool in a pre-prod and production envirronement. I can send you when done if you want.

Best Regards,
Yann

**Comment by rayrutjes** [comment]
Hello @yrmbrg, thanks for your detailed issue.
Would you be willing to open a Pull Request?

**Comment by eranchetz** [comment]
this works fine on edge (chromium) browser.
