### ISSUE TITLE
Can you provide instructions to setup this without docker?

### ISSUE THREAD

**Issue by planetahuevo** [algolia/sup3rS3cretMes5age#26]
Thanks

**Comment by eranchetz** [comment]
Hey @planetahuevo you basically need a vault server running somewhere, see instructions here https://www.vaultproject.io/docs/install/
and follow the Dockerfile to run the supersecret binary. 

Let us know if it makes sense.

I will add a more polished explanation in the docs later this week.

**Comment by planetahuevo** [comment]
Hi, 
It does. I thought this was a standalone version. 

Thanks!

**Comment by hijak** [comment]
please add details on what kinda of vault policy needs to be attached to the token
