### ISSUE TITLE
Custom certificates for nginx

### ISSUE THREAD

**Issue by stefcho034** [algolia/sup3rS3cretMes5age#32]
Hi!

Do you now how can I insert my custom certificates for the nginx image ? And also - stop using generation of letsencrypt certs generation ? 

Regards!

**Comment by Haroenv** [comment]
I don't maintain this project, but by reading: 

https://github.com/algolia/sup3rS3cretMes5age/blob/0222006ee58f2eadf909f753a3a534e5dd2f1782/nginx/nginx.tmpl#L95


I think you can have a default certificate with that file patch.

**Comment by stefcho034** [comment]
Yes, I think so. 

I already renamed my cert and key as default.crt and default.key. I have copied them in nginx project folder - nginx/certs in and included the following in Dockerfile:

FROM nginx:latest

COPY nginx/certs/default.crt etc/nginx/certs/default.crt
COPY nginx/certs/default.key etc/nginx/certs/default.key

That is working scenario for cert replacement, but suppose that I have other mistake with nginx, because it start to use my cert and respond Internal Server Error 500

**Comment by eranchetz** [comment]
@stefcho034 I removed the nginx as a dependcy as I feel it wasn't "simple" enough, let me open a new issue with enabling this feature directly with the go code.
