### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by Shaltz** [algolia/sup3rS3cretMes5age#34]
Hi,

I'm trying to run sup3rS3cretMes5age for the first time, 
but I end up with this error when running the make run command :

```bash
No stopped containers
dep ensure -v
make: dep: Command not found
Makefile:8: recipe for target 'deps' failed
make: *** [deps] Error 127
```

I follow the instruction, installed GO, docker and docker compose... don't know what to do now :(

Ubuntu 18.04.4
go version go1.14.4 linux/amd64
Docker version 19.03.6, build 369ce74a3c
docker-compose version 1.26.0, build d4451659

someone can help ?

thanks in advance

**Comment by Shaltz** [comment]
I tried to run the docker-compose file and end up with this error this time :+1: 
```bash
ubuntu@ip-192-168-252-76:~/sup3rS3cretMes5age$ docker-compose up
WARNING: The CERT_NAME variable is not set. Defaulting to a blank string.
Building supersecret
Step 1/8 : FROM alpine:latest
 ---> a24bb4013296
Step 2/8 : EXPOSE 1234
 ---> Using cache
 ---> 1c715cf338a7
Step 3/8 : ENV     VAULT_ADDR     VAULT_TOKEN
 ---> Using cache
 ---> 299042ac1f29
Step 4/8 : RUN apk add --no-cache ca-certificates ;mkdir -p /opt/supersecret/static
 ---> Using cache
 ---> d1ef1f1d9d2c
Step 5/8 : WORKDIR /opt/supersecret
 ---> Using cache
 ---> 059a108f415b
Step 6/8 : COPY bin/sup3rs3cretMes5age /opt/supersecret
ERROR: Service 'supersecret' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder094318089/bin/sup3rs3cretMes5age: no such file or directory
```

does anyone knows how to get superSecretMessage to work using any method ?? Docker, go or black magic ?

Please help, I really need this tool to work


thanks in advance

**Comment by eranchetz** [comment]
Hey @Shaltz looks like there is a missing pre-requisite in the docs:
you will also need to install [Dep](https://github.com/golang/dep#installation)

let me know if it works after you installed it.

**Comment by Shaltz** [comment]
Hi, 
thanks for your reply

DEP (go-dep) was already installed...

Talking about the doc, I'm new to go, 
but it seems that, in contrary with what the doc says,
you dont "just" clone the repo and run
"make run-local VIRTUAL_HOST=secret.test" ??

You need to clone it into the /usr/local/go/src folder and
export GOPATH=/usr/local/go or did I misunderstand something ?

Please, could I get a step by step explanation on how to run this from the
repo or , even better, using docker ??

thanks in advance

**Comment by Shaltz** [comment]
Hi again, 

no one can give a real step by step guide on how to install SSM plz ?
I've been looking all around and I haven't found much info :( :(

thx in advance

**Comment by eranchetz** [comment]
@Shaltz please see https://github.com/algolia/sup3rS3cretMes5age/pull/35
