### ISSUE TITLE
Use custom certificates 

### ISSUE THREAD

**Issue by eranchetz** [algolia/sup3rS3cretMes5age#39]
We need an ability to run this with custom (i.e. not let's encrypt) TLS certificates
[Requested by @stefcho034]

**Comment by GuiTeK** [comment]
@eranchetz @stefcho034 this is now possible: https://github.com/algolia/sup3rS3cretMes5age#configuration-options

**Comment by stefcho034** [comment]
@GuiTeK Thanks I will try it!
