### ISSUE TITLE
replace travis.ci with G̵i̵t̵h̵u̵b̵ ̵A̵c̵t̵i̵o̵n̵s̵ CircleCI

### ISSUE THREAD

**Issue by eranchetz** [algolia/sup3rS3cretMes5age#44]
https://docs.github.com/en/free-pro-team@latest/actions

**Comment by julienbourdeau** [comment]
Hi Eran 👋 
We moved most (all?) of our repo to CircleCI. I believe it would be best to move this one there too 👍

**Comment by eranchetz** [comment]
message received 🖖
