### ISSUE TITLE
New to Docker containers

### ISSUE THREAD

**Issue by jbales-3795** [algolia/sup3rS3cretMes5age#49]
I have had SuperSecretMessage running on a Ubuntu server for almost a month now but I have a couple of issues:

1.  Whenever I restart the server, the docker container basically gets wiped out and I have to reinstall it. 
2.  I am unable to edit the code to put some custom branding on it so clients tend to trust a known logo more than a plain website. 

Can you direct me on how to keep the container running after a restart and how I can customize the webpage?

**Comment by GuiTeK** [comment]
1. You should use [Docker volumes](https://docs.docker.com/storage/volumes/) to have persistent data
2. You can edit `static/index.html` and `static/getmsg.html` to put some custom branding

Finally, you can use [Docker restart policies](https://docs.docker.com/config/containers/start-containers-automatically/) to have a container restart automatically whenever a container exits or when the Docker service restarts.
