### ISSUE TITLE
TLS handshake error: acme/autocert: missing certificate

### ISSUE THREAD

**Issue by maurosanchezg** [algolia/sup3rS3cretMes5age#51]
Hi everyone, not sure what I have to do to fix this TLS error when trying to `run docker-compose up --build -d` on my docker server. My docker-compose.yml file is following the steps to configure Auto TLS with HTTP > HTTPS redirection.
This is what the docker-compose logs -f shows me:

supersecret    | echo: http: TLS handshake error from IP:Port: acme/autocert: missing certificate
supersecret    | echo: http: TLS handshake error from IP:Port: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

**Comment by eranchetz** [comment]
Looks like https://github.com/golang/go/issues/39732 is causing this issue, 
I have updated the dependencies and released a new version, master branch is updated as well. 
please let me know if that fixes #51

**Comment by maurosanchezg** [comment]
Hey Eran, Thanks for taking a look 👍🏼 So, I cloned the master branch and tried to run again the docker containers but now I'm getting a new error.

supersecret    | echo: http: TLS handshake error from IP:Port acme/autocert: unable to satisfy "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12492599861" for domain "mydomain.com": no viable challenge type found
supersecret    | echo: http: TLS handshake error from IP:Port acme/autocert: missing certificate

I have port both ports 80 and 443 opened and DNS entry is in place, Manual TLS works fine fwiw. Maybe something is still missing?

**Comment by Shaltz** [comment]
Hi all, 

Any update on this issue ? I am facing the same problem now :(

```bash
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v3.3.10-dev
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ https server started on [::]:443
⇨ http server started on [::]:80
echo: http: TLS handshake error from 172.16.200.195:50982: acme/autocert: unable to satisfy "https://acme-v02.api.letsencrypt.org/acme/authz-v3/14226727678" for domain "secret.mydomain.io": no viable challenge type found
echo: http: TLS handshake error from 172.16.200.195:13820: acme/autocert: missing certificate
echo: http: TLS handshake error from 172.16.200.195:10025: acme/autocert: missing certificate


```

I have pulled from git today, and running on the master branch...

any idea ?

**Comment by eranchetz** [comment]
Upgraded to Echov4, which solves auto-cert issues
https://echo.labstack.com/guide/migration/
