### ISSUE TITLE
Errors in README

### ISSUE THREAD

**Issue by Shaltz** [algolia/sup3rS3cretMes5age#56]
Hi, 

the README seems to be wrong, 
about the 
`VAULT_ADDR=http://vault:8200
VAULT_TOKEN=root

SUPERSECRETMESSAGE_HTTP_BINDING_ADDRESS=:80
SUPERSECRETMESSAGE_HTTPS_BINDING_ADDRESS=:443
SUPERSECRETMESSAGE_HTTPS_REDIRECT_ENABLED=true
SUPERSECRETMESSAGE_TLS_AUTO_DOMAIN=secrets.example.com`

I always get an error :
`ERROR: yaml.scanner.ScannerError: while scanning a simple key                                                                                
  in "/home/me/supersecret/docker-compose.yml", line 21, column 7
could not find expected ':'                                           
  in "/home/me/supersecret/docker-compose.yml", line 22, column 7 `

when I follow the instructions...

Shouldn't it be :
`VAULT_ADDR: http://vault:8200
VAULT_TOKEN: root

SUPERSECRETMESSAGE_HTTP_BINDING_ADDRESS: ":80"
SUPERSECRETMESSAGE_HTTPS_BINDING_ADDRESS: ":443"
SUPERSECRETMESSAGE_HTTPS_REDIRECT_ENABLED: "true"
SUPERSECRETMESSAGE_TLS_AUTO_DOMAIN: "secrets.example.com"`

my docker-compose version is
`docker-compose version 1.29.2, build unknown`

**Comment by Shaltz** [comment]
I did a pull request to fix the issues => #58

**Comment by eranchetz** [comment]
the examples in the README.md file are in pure bash and you are referring to docker-compose.yml format. 
maybe we should add more docker-compose examples 🤔
