### ISSUE TITLE
The vault is running in DEV Mode

### ISSUE THREAD

**Issue by Shaltz** [algolia/sup3rS3cretMes5age#62]
Hi, 

according to the logs, the Vault is running in Dev Mode

```bash
vault          | WARNING! dev mode is enabled! In this mode, Vault runs entirely in-memory
vault          | and starts unsealed with a single unseal key. The root token is already
vault          | authenticated to the CLI, so you can immediately begin using Vault.
vault          | 
vault          | You may need to set the following environment variable:
vault          | 
vault          |     $ export VAULT_ADDR='http://0.0.0.0:8200'
vault          | 
vault          | The unseal key and root token are displayed below in case you want to
vault          | seal/unseal the Vault or re-authenticate.
vault          | 
vault          | Unseal Key: qlea5SkvMiLfsArRpyhm..vf.dg.fd..1/QvbXbN4Td4Bbs=
vault          | Root Token: supersecret
vault          | 
vault          | Development mode should NOT be used in production installations!
```

is this intended ?
nothing wrong with this ?
Have I missed something from the doc to set it up in Prod Mode ?

thanks in advance ;)

**Comment by eranchetz** [comment]
This is perfectly OK and works as intended, as the Vault server is being used enclaved in it's container and is used as an ephemeral backend with no outside network access, the risk here is very low. 
Vault in dev mode is working in-mem and is using exactly the same encryption methods as in production mode. 
You can always set your configuration to work with a production deployment of vault [here](https://github.com/algolia/sup3rS3cretMes5age/blob/master/docker-compose.yml#L19) if required.
