### ISSUE TITLE
High availability?

### ISSUE THREAD

**Issue by lonix1** [algolia/sup3rS3cretMes5age#68]
Quick question please...

I see the backend is vault.

I assume when vault goes down (e.g. server restarts, docker container restarts/upgraded), all the temporary passwords are lost? I don't think this is a problem because this is a one-time password store. I'm just trying to understand how it works.

Thank you, and well done on creating such a clever and useful tool!

**Comment by eranchetz** [comment]
Yes vault is our backend, we are not security experts and we wanted to
offload that to those who are ;)

Indeed if vault goes down all one-time secrets are lost.
Multiple companies have been running this tool and haven’t experienced any
issues in the past.

Thank you for the kind words, it’s always nice to hear 💪
