### ISSUE TITLE
Running locally - errors

### ISSUE THREAD

**Issue by dvlden** [algolia/sup3rS3cretMes5age#8]
I followed the installation guide and I keep getting errors. I want to contribute to front-end part...

Running command `go get` just get stuck for some time and then there's nothing to install, and running `go run *.go` allows me to run it locally, but then HashiCorp Vault does not seem to work. It throws an error in network POST request when I try to submit message and since I don't know `go-lang` it's either problem with it, with a docker or with this project itself.

I wish if I could provide more detailed errors, but I uninstalled everything and tried multiple times and then ended up getting rid of everything as I was unable to make it work.

Steps I had to do before following the guide in README:

> Install GO via homebrew 

`brew install go`

> Add some `GO` related variables into my `.zshrc` and update the `PATH`

```bash
GOPATH=$HOME/.go
GOROOT=/usr/local/opt/go/libexec/bin
PATH=$GOROOT:$PATH
```

> Add given `VAULT` variables

```bash
VAULT_ADDR=http://localhost:8200
VAULT_TOKEN=$(docker logs vault | grep Token | awk '{print $NF}')
```

> Install Docker via homebrew-cask, then run the app

`brew cask install docker`

> Run given command for HashiCorp Vault _(assuming)_ for Docker

`docker run -ti --cap-add=IPC_LOCK -ti -p 8200:8200  --name vault vault`

> And of course final steps

```bash
cd ~/Sites
git clone https://github.com/algolia/sup3rS3cretMes5age.git
cd sup3rS3cretMes5age
go get
go run *.go
```

And of course then as I described, I keep getting some errors. I can install `go` and `docker` again if you could help me to resolve this issue more easily?

**Comment by dvlden** [comment]
> After reinstalling everything when I run following command:

`go get`

After a short period of time, console outputs following:

```bash
go install: no install location for directory /Users/nn/Sites/sup3rS3cretMes5age outside GOPATH
For more details see: 'go help gopath'
```

**Comment by eranchetz** [comment]
@dvlden sorry for the late response and thanks for the detailed issue, we have changed the deployment/running process. can you please try again now?

BTW usually: 
```
go install: no install location for directory /Users/nn/Sites/sup3rS3cretMes5age outside GOPATH
For more details see: 'go help gopath'
```
is not an error but just a warning, please try to run sup3rS3cretMes5age even if you get the above message.

**Comment by dvlden** [comment]
@eranchetz - Now it works!

Well, I did try that, but it was unable to submit the form request. Now it's all good...

Appreciate the updates.

**Comment by eranchetz** [comment]
@dvlden nice to know. I hope sup3rS3cretMes5age is useful to you.
